**[Slide No. 5]**

1. Write a Program to check the version numpy installed .

**[Slide No . 8]**

2. Write a program to create numpy 1-D array from list.

**[Slide No. 9]**

3. Write a program to Create a 2-D array .

**[Slide No . 11]**

5. a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])



What is the output [5 9] ?

**[Slide No.15]**

6. Correct the program .

import numpy as np

array=np.array([1,2,3,4,5,6])

print(array[-1:-5])

In [28]:
array = np.array([1,2,3,4,5,6])

print(array[-5:-1])

[2 3 4 5]


7. a=np.array([(1,5,9),(10,12,2),(5,7,8)])


Print the max value from first row ?

print min value from the first row ?

print the sum of all the element of second row ?




In [2]:
a=np.array([(1,5,9),(10,12,2),(5,7,8)])
a

array([[ 1,  5,  9],
       [10, 12,  2],
       [ 5,  7,  8]])

In [23]:
import numpy as np
np1=np.random.randint(2,9,(3,2,3,4))
np1.ndim

4

In [20]:
np1[0].sum()

21

**[Slide No. 16]**


8. Create a numpy array using a below numbers and print (1,3,5).

[1,2,3,4,5,6]



In [ ]:
i%2==1

**[Slide No. 18]**

9. Create a  [3,4] numpy array and reshape it [4,3] numpy array.

**[Slide No. 20]**

10. Create two numpy array and concanate them .

**[Slide No.22]**

11. Create numpy array and search a number in it .

In [26]:
a=np.arange(0,5)
np.where(a==4)

(array([4]),)

**[Slide No.26]**

12. Write a program to print 3,4 numpy array by any random number using random.randint function

**[Slide No. 30]**

13. Write a program to add two numpy array.

14. Delete the second column from a given array and insert the following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = numpy.array([[10,10,10]])

In [1]:
import numpy as np


In [30]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 1, axis = 0)
print(sampleArray)
sampleArray = np.insert(sampleArray, 1, newColumn, axis = 0)
#print(sampleArray)

[[34 43 73]
 [53 94 66]]


In [31]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [32]:
sampleArray[:,1]=[10,10,10]

In [33]:
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])